
services:
  app:
    networks:
      - net
    build:
      context: .
      dockerfile: Dockerfile
    container_name: doacoes
    ports:
      - '8000:8000'
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env


  db:
    image: postgres
    networks:
      - net
    ports: 
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env

volumes:
  postgres_data:  

networks:
  net:
    driver: bridge