# Imagem oficial do Python utilizada na aplicação
FROM python:3.10-slim


WORKDIR /app

# Copiando os arquivos de dependências para o container
COPY ./requirements.txt .

RUN python -m pip install --upgrade pip

# Instalação das dependências
RUN pip install --no-cache-dir -r requirements.txt

# Copiando o conteúdo do projeto para o diretório de trabalho
COPY . .

# Porta da aplicação
EXPOSE 8000

# Comando para iniciar a aplicação FastAPI
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
